CREATE OR REPLACE FUNCTION refresh_turmasmedianotas() 
RETURNS TRIGGER AS $$
BEGIN
  REFRESH MATERIALIZED VIEW TurmasMediaNotas;
  RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER refresh_view
AFTER INSERT ON Avaliacoes
FOR EACH ROW EXECUTE PROCEDURE refresh_turmasmedianotas();
